topic_meta_list:
- topic_name: /agivslam/localization/odometry
  msg_type: ros2:nav_msgs/msg/Odometry
- topic_name: /agivslam/map
  msg_type: ros2:sensor_msgs/msg/PointCloud2
- topic_name: /agivslam/reloc_image
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/bms/data
  msg_type: pb:aimdk.protocol.BmsStateChannel
- topic_name: /aima/emergency_state
  msg_type: pb:aimdk.protocol.EmergencyStateChannel
- topic_name: /aima/fill_light
  msg_type: pb:aimdk.protocol.FillLightStateChannel
- topic_name: /aima/hal/camera/interactive/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/camera/interactive/color/h264
  msg_type: ros2:foxglove_msgs/msg/CompressedVideo
- topic_name: /aima/hal/fish_eye_camera/chest_left/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/fish_eye_camera/chest_left/color/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hal/fish_eye_camera/chest_left/color/h264
  msg_type: ros2:foxglove_msgs/msg/CompressedVideo
- topic_name: /aima/hal/fish_eye_camera/chest_right/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/fish_eye_camera/chest_right/color/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hal/fish_eye_camera/chest_right/color/h264
  msg_type: ros2:foxglove_msgs/msg/CompressedVideo
- topic_name: /aima/hal/imu/chassis_center/imu
  msg_type: ros2:sensor_msgs/msg/Imu
- topic_name: /aima/hal/lidar/neck/imu
  msg_type: ros2:sensor_msgs/msg/Imu
- topic_name: /aima/hal/lidar/neck/pointcloud
  msg_type: ros2:sensor_msgs/msg/PointCloud2
- topic_name: /aima/hal/lidar/top/imu
  msg_type: ros2:sensor_msgs/msg/Imu
- topic_name: /aima/hal/lidar/top/pointcloud
  msg_type: ros2:sensor_msgs/msg/PointCloud2
- topic_name: /aima/hal/rgbd_camera/chassis_front/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/chassis_front/depth
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/hand_front/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/hand_front/color/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hal/rgbd_camera/hand_front/depth
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/hand_front/depth/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hal/rgbd_camera/hand_left/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/hand_left/depth
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/hand_right/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/hand_right/depth
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/head_front/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/head_front/color/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hal/rgbd_camera/head_front/color/h264
  msg_type: ros2:foxglove_msgs/msg/CompressedVideo
- topic_name: /aima/hal/rgbd_camera/head_front/depth
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/waist_front/color
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/waist_front/color/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hal/rgbd_camera/waist_front/color/h264
  msg_type: ros2:foxglove_msgs/msg/CompressedVideo
- topic_name: /aima/hal/rgbd_camera/waist_front/depth
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /aima/hal/rgbd_camera/waist_front/depth/compressed
  msg_type: ros2:sensor_msgs/msg/CompressedImage
- topic_name: /aima/hds/alert
  msg_type: pb:aimdk.protocol.AlertChannel
- topic_name: /aima/hds/exception
  msg_type: pb:aimdk.protocol.ModuleExceptionChannel
- topic_name: /aima/hds/fallback
  msg_type: pb:aimdk.protocol.FallbackChannel
- topic_name: /aima/hds/health_status
  msg_type: pb:aimdk.protocol.HealthStatusChannel
- topic_name: /aima/hds/system_status_soc0
  msg_type: pb:aimdk.protocol.SystemStatusChannel
- topic_name: /aima/hds/system_status_soc1
  msg_type: pb:aimdk.protocol.SystemStatusChannel
- topic_name: /aima/heartbeat
  msg_type: pb:aimdk.protocol.ProcessHeartbeatChannel
- topic_name: /aima/light_strip
  msg_type: pb:aimdk.protocol.LightStripStateChannel
- topic_name: /aima/log/module_log
  msg_type: pb:aimrt.protocols.topic_logger.LogData
- topic_name: /aima/rgb_light
  msg_type: pb:aimdk.protocol.RgbLightStateChannel
- topic_name: /aima/robot_state
  msg_type: pb:aimdk.protocol.RobotHeartBeatChannel
- topic_name: /aimrte/sm/node_state
  msg_type: pb:aimdk.protocol.SmNodeStateChannel
- topic_name: /aimrte/trace/events
  msg_type: pb:aimdk.protocol.EventChannel
- topic_name: /arm_joint_servo/joint_command
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /arm_joint_servo/joint_state
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /aruco/target_pose
  msg_type: ros2:geometry_msgs/msg/PoseStamped
- topic_name: /aruco_detector/debug
  msg_type: ros2:sensor_msgs/msg/Image
- topic_name: /body_drive/arm_joint_command
  msg_type: ros2:joint_msgs/msg/JointCommand
- topic_name: /body_drive/arm_joint_state
  msg_type: ros2:joint_msgs/msg/JointState
- topic_name: /body_drive/arm_pose_command
  msg_type: ros2:hal_msgs/msg/PoseCommand
- topic_name: /body_drive/arm_pose_state
  msg_type: ros2:hal_msgs/msg/PoseStates
- topic_name: /body_drive/claw_joint_command
  msg_type: pb:aimdk.protocol.HandCommandChannel
- topic_name: /body_drive/claw_joint_state
  msg_type: ros2:hal_msgs/msg/JointState
- topic_name: /body_drive/foot_sensor_state
  msg_type: ros2:sensors_msgs/msg/FootSensorState
- topic_name: /body_drive/hand_joint_command
  msg_type: pb:aimdk.protocol.HandCommandChannel
- topic_name: /body_drive/hand_joint_state
  msg_type: pb:aimdk.protocol.HandStateChannel
- topic_name: /body_drive/imu/data
  msg_type: ros2:sensor_msgs/msg/Imu
- topic_name: /body_drive/leg_joint_command
  msg_type: ros2:joint_msgs/msg/JointCommand
- topic_name: /body_drive/leg_joint_state
  msg_type: ros2:joint_msgs/msg/JointState
- topic_name: /body_drive/leg_temp_state
  msg_type: ros2:temp_msgs/msg/TempState
- topic_name: /body_drive/lift_joint_command
  msg_type: ros2:hal_msgs/msg/JointCommand
- topic_name: /body_drive/lift_joint_state
  msg_type: ros2:hal_msgs/msg/JointState
- topic_name: /body_drive/neck_joint_command
  msg_type: ros2:joint_msgs/msg/JointCommand
- topic_name: /body_drive/neck_joint_state
  msg_type: ros2:joint_msgs/msg/JointState
- topic_name: /body_drive/power/data
  msg_type: ros2:power_msgs/msg/PowerState
- topic_name: /body_drive/waist_joint_command
  msg_type: ros2:hal_msgs/msg/JointCommand
- topic_name: /body_drive/waist_joint_state
  msg_type: ros2:hal_msgs/msg/JointState
- topic_name: /body_drive/wheel_joint_command
  msg_type: ros2:hal_msgs/msg/JointCommand
- topic_name: /body_drive/wheel_joint_state
  msg_type: ros2:hal_msgs/msg/JointState
- topic_name: /cmd_vel
  msg_type: ros2:geometry_msgs/msg/Twist
- topic_name: /cmd_vel_final
  msg_type: ros2:geometry_msgs/msg/Twist
- topic_name: /costmap/costmap1
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /costmap/costmap1_updates
  msg_type: ros2:nav_msgs/msg/OccupancyGridUpdate
- topic_name: /costmap/costmap1_updates_map
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /costmap/published_footprint
  msg_type: ros2:geometry_msgs/msg/PolygonStamped
- topic_name: /costmap_update_map
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /dbg_cmd_vel
  msg_type: ros2:geometry_msgs/msg/Twist
- topic_name: /dbg_collision_check_path
  msg_type: ros2:visualization_msgs/msg/MarkerArray
- topic_name: /dbg_collision_pose
  msg_type: ros2:visualization_msgs/msg/MarkerArray
- topic_name: /dbg_ctrl_path
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /dbg_global_path
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /dbg_polygon_visualize
  msg_type: ros2:visualization_msgs/msg/MarkerArray
- topic_name: /dbg_static_map
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /four_wheel_car_cmd
  msg_type: ros2:std_msgs/msg/Float64MultiArray
- topic_name: /hal_state/emergency
  msg_type: pb:aimdk.protocol.EmergencyStateChannel
- topic_name: /legged_odometry/mode
  msg_type: ros2:std_msgs/msg/Int32MultiArray
- topic_name: /legged_odometry_node/legged_odometry
  msg_type: ros2:nav_msgs/msg/Odometry
- topic_name: /loc/final_cloud
  msg_type: ros2:sensor_msgs/msg/PointCloud2
- topic_name: /loc/target_point
  msg_type: ros2:sensor_msgs/msg/PointCloud2
- topic_name: /loc_tele/current_pose
  msg_type: pb:aimdk.protocol.PubCurrentPose
- topic_name: /loc_tele/image
  msg_type: pb:aimdk.protocol.PubImageData
- topic_name: /loc_tele/qr_localization_pose
  msg_type: pb:aimdk.protocol.QRDetectionResult
- topic_name: /loc_tele/relocalization_image
  msg_type: pb:aimdk.protocol.PubImageData
- topic_name: /loc_tele/relocalization_pcd
  msg_type: pb:aimdk.protocol.PubRelocalizationRealtimeLidarPoints
- topic_name: /loc_tele/relocalization_result
  msg_type: pb:aimdk.protocol.PubRelocalizationResult
- topic_name: /map
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /mapping_tele/realtime_2d_map
  msg_type: pb:aimdk.protocol.Map2DRealtimeMapData
- topic_name: /mapping_tele/saving_percent
  msg_type: pb:aimdk.protocol.MapSavingProcessData
- topic_name: /mc/base/state
  msg_type: pb:aimdk.protocol.McStateChannel
- topic_name: /mc/kinematics/foot_kine
  msg_type: pb:aimdk.protocol.FootKinematicsChannel
- topic_name: /motion/control/arm_joint_command
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /motion/control/arm_joint_state
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /motion/control/hand_command
  msg_type: pb:aimdk.protocol.HandCommandChannel
- topic_name: /motion/control/hand_joint_command
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /motion/control/hand_joint_state
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /motion/control/locomotion_velocity
  msg_type: pb:aimdk.protocol.McLocomotionVelocityChannel
- topic_name: /motion/control/move_waist
  msg_type: pb:aimdk.protocol.McMoveWaistChannel
- topic_name: /motion/control/move_waist_lift
  msg_type: pb:aimdk.protocol.McMoveWaistLiftChannel
- topic_name: /motion/control/move_waist_pitch
  msg_type: pb:aimdk.protocol.MotorWaistPitchChannel
- topic_name: /motion/control/move_waist_sideways
  msg_type: pb:aimdk.protocol.McMoveWaistSidewaysChannel
- topic_name: /motion/control/move_waist_twist
  msg_type: pb:aimdk.protocol.McMoveWaistTwistChannel
- topic_name: /motion/control/neck_joint_command
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /motion/control/neck_joint_state
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /motion_streamer/mocap_data_status
  msg_type: pb:aimdk.protocol.McStateChannel
- topic_name: /multi_scale_objects
  msg_type: ros2:aruco_msgs/msg/ArucoDetections
- topic_name: /nv_cam_lidar_percep/occupancy_3d
  msg_type: pb:aimdk.protocol.PerceptionOcc3D
- topic_name: /osmonitor/event
  msg_type: pb:aimdk.protocol.IoPackets
- topic_name: /path
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /path_local
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /pnc/estimate_odom
  msg_type: ros2:nav_msgs/msg/Odometry
- topic_name: /pnc/estimate_pose_vel
  msg_type: ros2:geometry_msgs/msg/Twist
- topic_name: /pnc/recv_mc_vel
  msg_type: ros2:geometry_msgs/msg/Twist
- topic_name: /ranger_base_node/odom
  msg_type: ros2:nav_msgs/msg/Odometry
- topic_name: /rc/data
  msg_type: pb:aimdk.protocol.RemoteControlChannel
- topic_name: /root/ros2_bridge_node/controller_server_ros_node/MPPIController/dbg_path
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /root/ros2_bridge_node/controller_server_ros_node/MPPIController/dbg_trajectories
  msg_type: ros2:visualization_msgs/msg/MarkerArray
- topic_name: /root/ros2_bridge_node/planner_server_ros_node/GridBased/path
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /root/ros2_bridge_node/planner_server_ros_node/GridBased/potential
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /root/ros2_bridge_node/planner_server_ros_node/GridBasedAstar/path
  msg_type: ros2:nav_msgs/msg/Path
- topic_name: /root/ros2_bridge_node/planner_server_ros_node/GridBasedAstar/potential
  msg_type: ros2:nav_msgs/msg/OccupancyGrid
- topic_name: /ros2_debug/fusion
  msg_type: ros2:nav_msgs/msg/Odometry
- topic_name: /ros2_debug/imu
  msg_type: ros2:sensor_msgs/msg/Imu
- topic_name: /ros2_debug/joint_commands_active
  msg_type: ros2_data_type::msg::JointCommand
- topic_name: /ros2_debug/joint_commands_active_total
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /ros2_debug/joint_commands_serial
  msg_type: ros2_data_type::msg::JointCommand
- topic_name: /ros2_debug/joint_states_active
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /ros2_debug/joint_states_serial
  msg_type: ros2:sensor_msgs/msg/JointState
- topic_name: /ros2_debug/user_command
  msg_type: ros2:nav_msgs/msg/Odometry
- topic_name: /task_engine/heartbeat
  msg_type: pb:aimdk.protocol.TaskEngineHeartBeat
- topic_name: /tf
  msg_type: ros2:tf2_msgs/msg/TFMessage
- topic_name: /tf_static
  msg_type: ros2:tf2_msgs/msg/TFMessage
- topic_name: /trajectories
  msg_type: ros2:visualization_msgs/msg/MarkerArray
- topic_name: /transformed_global_plan
  msg_type: ros2:nav_msgs/msg/Path
